---
Name: slmenusetconfig
Only:
  moduleexists: silverstripe/subsite
---
Sitelease\MenuSets\Models\LinkMenuSet:
  extensions:
    - Sitelease\MenuSets\Extensions\LinkMenuSetSubsiteExtension
---
Only:
  moduleexists: 'silverstripe/graphql'
---
SilverStripe\GraphQL\Controller:
  schema:
    scaffolding_providers:
      - Sitelease\MenuSets\Models\LinkMenuSet
      - Sitelease\MenuSets\Models\MenuLink
