---
Name: menuconfig
Only:
  moduleexists: silverstripe/subsite
---
Sitelease\LinkMenu\Models\LinkMenuSet:
  extensions:
    - Sitelease\LinkMenu\Extensions\LinkMenuSetSubsiteExtension
---
Only:
  moduleexists: 'silverstripe/graphql'
---
SilverStripe\GraphQL\Controller:
  schema:
    scaffolding_providers:
      - Sitelease\LinkMenu\Models\LinkMenuSet
      - Sitelease\LinkMenu\Models\MenuLink
